persius/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('user.urls', namespace='profile')),
    path('', include('user.urls', namespace='userurl')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib.auth import login
from django.urls import path
from . import views

app_name = "user"
urlpatterns = [
    path('', views.index, name="home"),
    path('signup', views.signup, name="signup"),
    path('login', views.log_in, name="login"),
    path('logout', views.log_out, name="logout"),
    path('update/<int:user_id>/', views.update, name='update'),
    path('<int:user_id>/', views.profile, name='profile'),
    path('myposts', views.posts, name='myPosts'),
    path('post/<int:post_id>/', views.perticularPost, name='post'),
    path('createpost/<int:user_id>/', views.createpost, name='createPost'),

]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.db.models.deletion import CASCADE
from .managers import CustomUserManager
# Create your models here.


class User(AbstractUser):
    username = None
    # Id = models.AutoField
    email = models.EmailField(unique=True)
    age = models.IntegerField(null=True, blank=True)
    username = models.CharField(max_length=50, default="")
    address = models.TextField(default="")
    image = models.ImageField(upload_to ='user/images', null = True, blank = True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    object = CustomUserManager()

    def __str__(self):
        return self.email

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user")
    image = models.ImageField(upload_to ='post/images', null = True, blank = True)
    dsc = models.CharField(max_length=500)
    winner = models.CharField(max_length=100, null = True, blank = True)

    def __str__(self):
        return self.dsc
    pass

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=CASCADE, related_name="post")
    comment_user = models.ForeignKey(User, on_delete=CASCADE, related_name="comment_user")
    comment = models.CharField(max_length=100)

    def __str__(self):
        return self.comment_user.email

user/views.py
from django.http.request import validate_host
from django.shortcuts import render, redirect, HttpResponse
from .models import User, Post, Comment
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout


def index(request, *args, **kwargs):
    if request.user.is_anonymous:
        return redirect("/login")
    context = {}
    posts = Post.objects.all()
    context['posts'] = posts
    if request.method == "POST":
        commentDsc = request.POST.get('comment')
        postId = request.POST.get('post')
        commentUser = request.user
        try:
            post = Post.objects.get(pk=postId)
        except Post.DoesNotExist:
            return HttpResponse('Post does not exists')
        comment = Comment(post=post, comment_user=commentUser, comment=commentDsc)
        comment.save()
    return render(request, 'index.html', context)


def signup(request, *args, **kwargs):
    if request.method == "POST":
        username = request.POST['username']
        firstname = request.POST['fname']
        lastname = request.POST['lname']
        email = request.POST['email']
        age = request.POST['age']
        address = request.POST.get('address')
        image = request.FILES.get('image')
        password = request.POST['password']
        re_password = request.POST['re_password']

        # check for errorneous inputs
        if len(username) > 10:
            messages.error(request, "Username must be under 10 characters")
            return render(request, 'signup.html')
        if password != re_password:
            messages.error(request, "Passwords do not match")
            return render(request, 'signup.html')
        if int(age) < 12:
            messages.error(request, "Age must be greater than 12")
            return render(request, 'signup.html')

        # creat user
        new_user = User.objects.create_user(username, email, password, first_name=firstname, last_name=lastname, age=age, address=address, image=image)

        new_user.save()
        messages.success(request, 'Your account has been successfully created Please Login.')
    return render(request, 'signup.html')


def log_in(request):
    if request.method == "POST":
        # check that user login with correct credentials
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("/")
        else:
            return render(request, 'login.html')
    return render(request, 'login.html')


def log_out(request):
    logout(request)
    return redirect("/login")

def profile(request, *args, **kwargs):
    context = {}
    user_id = kwargs.get("user_id")

    if request.user.is_authenticated:
        try:
            account = User.objects.get(id=user_id)
        except User.DoesNotExist:
            return HttpResponse("user not found")

        # check that user is looking for own profile or not 
        if account == request.user:
            context['id'] = account.id
            context['username'] = account.username
            context['first_name'] = account.first_name
            context['last_name'] = account.last_name
            context['age'] = account.age
            context['email'] = account.email
            context['address'] = account.address
            context['image'] = account.image.url
            return render(request, 'profile.html', context)
        else:
            return HttpResponse("You can not see others profile.")
    else:
        return redirect("/login")

def update(request, *args, **kwargs):
    if not request.user.is_authenticated:
        return redirect("/login")
    user_id = kwargs.get("user_id")
    try:
        account = User.objects.get(pk=user_id)
    except User.DoesNotExist:
        return HttpResponse("Something went wrong")
    if account.pk != request.user.pk:
        return HttpResponse("You cannot edit someone elses profile")
    context = {}

    if request.POST:
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        username = request.POST['username']
        age = request.POST['age']
        address = request.POST['address']
        email = request.POST['email']
        image = request.FILES.get('image')

        # checking if user wants to change profile too
        if image is not None:
            image = request.FILES.get('image')

        # validating username and age 
        if len(username) > 10:
            messages.error(request, "Username must be under 10 characters")
            return redirect(f"/update/{request.user.pk}")
        if int(age) < 12:
            messages.error(request, "Age must be greater than 12")
            return redirect(f"/update/{request.user.pk}")
        account.first_name = firstname
        account.last_name = lastname
        account.username = username
        account.age = age
        account.address = address
        account.email = email
        if image:
            account.image = image
        account.save()
    
    # sending data to front end 
    context['id'] = account.id
    context['username'] = account.username
    context['first_name'] = account.first_name
    context['last_name'] = account.last_name
    context['age'] = account.age
    context['email'] = account.email
    context['address'] = account.address
    context['image'] = account.image.url
    return render(request, 'update.html', context)


def posts(request, *args, **kwargs):
    if request.user.is_authenticated:

        user = request.user
        context = {}
        try:
            posts = Post.objects.filter(user=user)
        # In this case may be user hasn't make any post
        except Post.DoesNotExist:
            posts = None
        context['posts'] = posts
        return render(request, 'mypost.html', context)
    else:
        return redirect("/login")

def perticularPost(request, *args, **kwargs):
    if request.user.is_authenticated:
        context = {}
        user = request.user
        postId = kwargs.get('post_id')

        try:
            post = Post.objects.get(pk=postId)
        except Post.DoesNotExist:
            return HttpResponse("Post not found")

        # this will check wheater you are opening your post or others post 
        if user != post.user:
            return HttpResponse("You are not allowed to be here")

        if request.method == "POST":
            winner_name = request.POST['winner']
            post.winner = winner_name
            post.save()
            pass
        try:
            comments = Comment.objects.filter(post=post)
            context['comments'] = comments
        # when no comments are there 
        except Comment.DoesNotExist:
            context['comments'] = None

        context['post'] = post
        return render(request, 'perticularPost.html', context)
    else:
        return redirect("/login")
        

def createpost(request, *args, **kwargs):
    user = request.user
    if user.is_authenticated:
        if request.method == "POST":
            user = request.user
            description = request.POST['details']
            image = request.FILES.get('image')

            # now creating new post 
            post = Post(user=user, image=image, dsc=description)
            post.save()
            messages.success(request, 'Your post is live now')
    else:
        return redirect("/login")
    return render(request, 'createpost.html')

user/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>{% block title %}{% endblock title %}</title>
    <link href="https://fonts.googleapis.com/css2?family=Baloo+Chettan+2&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/static/base.css">
    <link rel="stylesheet" href="/static/login.css">
    <link rel="stylesheet" href="/static/index.css">
    <link rel="stylesheet" href="/static/signup.css">
    <link rel="stylesheet" href="/static/mypost.css">
    <link rel="stylesheet" href="/static/profile.css">
    <link rel="stylesheet" href="/static/perticularPost.css">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">NikChat</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation" style="margin: 0;">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if request.user.id != None %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'profile:profile' user_id=request.user.id %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'user:myPosts'%}">My Posts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'user:createPost' user_id=request.user.id %}">Create Post</a>
                    </li> 
                    {% endif %}
                </ul>
                {% if user.is_authenticated %}
                <div class="btn-group mx-2">
                    <button type="button" class="btn btn-outline-success dropdown-toggle" data-bs-toggle="dropdown"
                        aria-expanded="false" style="position: relative; left: -8px; margin:0;">
                        Welcome {{request.user.first_name}}
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="/logout">Logout</a></li>
                    </ul>
                </div>
                {% else %}
                <div class="button"><a href="/login" class="btn btn-outline-success mx-2">Login</a></div>
                <div class="button"><a href="/signup" class="btn btn-outline-success">Sign Up</a></div>
                {% endif %}
            </div>
        </div>
    </nav>

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show my-0" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    {% block body %} {% endblock body %}
    <footer class="blog-footer">
        <p>&copy; 2021-2022 Website developed by Nitin Goswami</p>
        <p>Email us at- nitingoswami1900@gmail.com</p>
        <p>
            <a href="#">Back to top</a>
        </p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

user/templates/createpost.html
{% extends 'base.html' %}
{% block title %}Create Post{% endblock title %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container my-5">
        <div class="mb-3">
            <label for="formFile" class="form-label">Picture of Place</label>
            <input class="form-control" type="file" id="formFile" name="image" required>
        </div>
        <div class="input-group">
            <span class="input-group-text">Place details</span>
            <textarea class="form-control" aria-label="With textarea" name="details" required></textarea>
        </div>
        <button type="submit" class="btn btn-primary my-3">Submit</button>
    </div>
</form>

{% endblock body %}

user/templates/index.html
{% extends 'base.html' %}
{% block title %}Login{% endblock title %}
{% block body %}
<div class="postbody">
    {% for post in posts %}
    <div class="postbox">
        <div class="image">
            <img src="{{post.image.url}}" alt="">
        </div>
        <div class="name">
            Post by: {{post.user.first_name}} {{post.user.last_name}}
        </div>
        <div class="discription">
            Discription: {{post.dsc}}
        </div>
        {% if post.winner != None %}
        <div class="winner">
            Winner Name: {{post.winner}}
        </div>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="comment">
                <input type="text" name="comment" placeholder="Comment">
                <input type="number" name="post" id="post-id" value="{{post.id}}">
                <button type="submit">Send</button>
            </div>
        </form>
    </div>
    {% endfor %}
</div>

{% endblock body %}

user/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock title %}
{% block body %}

<div id="form-login">
  <form class="p-5 border rounded-3 bg-light" method="POST">
      {% csrf_token %}
    <div class="form-floating mb-3">
      <input type="text" class="form-control" id="floatingInput" name="username" placeholder="Email">
      <label for="floatingInput">Email</label>
    </div>
    <div class="form-floating mb-3">
      <input type="password" class="form-control" id="floatingPassword" name="password" placeholder="Password">
      <label for="floatingPassword">Password</label>
    </div>
    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Login</button>
    <hr class="my-4">
    <small class="text-muted">By clicking Sign up, you agree to the terms of use.</small>
  </form>
</div>
{% endblock body %}

user/templates/mypost.html
{% extends 'base.html' %}
{% block title %}My Post{% endblock title %}
{% block body %}
<div class="postbody">
    {% for post in posts %}
    <div class="postbox">
        <div class="image">
            <img src="{{post.image.url}}" alt="">
        </div>
        <div class="discription">
            Discription: {{post.dsc}}
        </div>
        {% if post.winner != None %}
        <div class="winner">
            Winner Name: {{post.winner}}
        </div>
        {% endif %}
        <div class="view">
            <a href="{% url 'user:post' post_id=post.id%}">View</a>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock body %}

user/templates/perticularPost.html
{% extends 'base.html' %}
{% block title %}Post{% endblock title %}
{% block body %}

<div class="postbody">
    <div class="postbox">
        <div class="image">
            <img src="{{post.image.url}}" alt="">
        </div>
        <div class="discription">
            Discription: {{post.dsc}}
        </div>
    </div>
    <div class="outerbody">
        <div class="comments-body">
            <h3>Comments</h3>
            {% for comment in comments %}
            <div class="comment">
                <span>{{comment.comment_user.first_name}} {{comment.comment_user.last_name}}: </span>
                <span>{{comment.comment}}</span>
            </div>
            {% endfor %}
        </div>
        <div class="winner-body">
            <form method="POST">
                {% csrf_token %}
                {% if post.winner != None %}
                <h4>Winner: {{post.winner}}</span>
                <input type="text" name="winner" placeholder="Change Winner" required>
                {% else %}
                <input type="text" name="winner" placeholder="Winner" required>
                {% endif %}
                <button>Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock body %}

user/templates/profile.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock title %}
{% block body %}

<div class="container profile-container">
    <div class="image">
        <img src="{{image}}" alt="dp">
    </div>
    <div class="details">
        <span class="name">{{first_name}} {{last_name}}</span>
        <span class="username">Username: {{username}}</span>
        <span class="age">Age: {{age}}</span>
        <span class="email">Email: {{email}}</span>
        <span class="address">Address: {{address}}</span>
    </div>
    <div class="update">
        <a href="{% url 'user:update' user_id=request.user.id%}">Update Profile</a>
    </div>
</div>

{% endblock body %}

user/templates/signup.html
{% extends 'base.html' %}
{% block title %}SignUp{% endblock title %}
{% block body %}

<div class="signup">
    <form class="p-5 border rounded-3 bg-light" id="signup-form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-floating mb-3">
            <input type="text" class="form-control" id="floatingInput" name="username" placeholder="Username" required>
            <label for="floatingInput">Username</label>
        </div>
        <div class="form-floating mb-3">
            <input type="text" class="form-control" id="floatingInput" name="fname" placeholder="First name" required>
            <label for="floatingInput">First name</label>
        </div>
        <div class="form-floating mb-3">
            <input type="text" class="form-control" id="floatingInput" name="lname" placeholder="Last name" required>
            <label for="floatingInput">Last name</label>
        </div>
        <div class="form-floating mb-3">
            <input type="number" class="form-control" id="floatingInput" name="age" placeholder="age" required>
            <label for="floatingInput">Age</label>
        </div>
        <div class="form-floating mb-3">
            <input type="email" class="form-control" id="floatingInput" name="email" placeholder="name@example.com" required>
            <label for="floatingInput">Email address</label>
        </div>
        <div class="form-floating mb-3">
            <input type="text" class="form-control" id="floatingInput" name="address" placeholder="Address" required>
            <label for="floatingInput">Address</label>
        </div>
        <div class="form-floating mb-3">
            <input type="file" class="form-control" id="floatingInput" name="image" placeholder="Profile Picture" required>
            <label for="floatingInput">Profile Picture</label>
        </div>
        <div class="form-floating mb-3">
            <input type="password" class="form-control" id="floatingPassword" name="password" placeholder="Password" required>
            <label for="floatingPassword">Password</label>
        </div>
        <div class="form-floating mb-3">
            <input type="password" class="form-control" id="floatingPassword" name="re_password" placeholder="Repeat Password" required>
            <label for="floatingPassword">Repeat Password</label>
        </div>
        
        <button class="w-100 btn btn-lg btn-primary" type="submit">Sign-up</button>
        <hr class="my-4">
        <small class="text-muted">By clicking Sign up, you agree to the terms of use.</small>
    </form>
</div>
{% endblock body %}

user/templates/update.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock title %}
{% block body %}

<div class="container profile-container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="image">
            <img src="{{image}}" alt="dp">
            <input type="file" name="image">
        </div>
        <div class="details">
            <input type="text" name="firstname" value={{first_name}}>
            <input type="text" name="lastname" value={{last_name}}>
            <input type="text" name="username" value={{username}}>
            <input type="number" name="age" value={{age}}>
            <input type="email" name="email" value={{email}}>
            <input type="text" name="address" value={{address}}>
        </div>
        <div class="submit">
            <button type='submit'>Submit</button>
        </div>
    </form>
</div>

{% endblock body %}